# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'USCChannel' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for USCChannel
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'

  target 'USCChannelTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'USCChannel-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for USCChannel-tvOS

  target 'USCChannel-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end