# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'USCChannel' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  rn_path = '../node_modules/react-native'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]
  
  # Pods for USCChannel
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'

  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'
  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'
  pod 'react-native-pdf', :path => '../node_modules/react-native-pdf'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  target 'USCChannelTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'USCChannel-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for USCChannel-tvOS

  target 'USCChannel-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end