# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'USCChannel' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  rn_path = '../node_modules/react-native'
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation',
    'RCTImage'
  ]

  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  # Pods for USCChannel
  pod 'Firebase/Core', '~> 5.20.1'
  pod 'Firebase/Auth', '~> 5.20.1'
  pod 'Firebase/Storage', '~> 5.20.1'

  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'
  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'
  pod 'react-native-pdf', :path => '../node_modules/react-native-pdf'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  target 'USCChannelTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'USCChannel-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for USCChannel-tvOS

  target 'USCChannel-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end